// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// MoveHostHandlerFunc turns a function with the right signature into a move host handler
type MoveHostHandlerFunc func(MoveHostParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn MoveHostHandlerFunc) Handle(params MoveHostParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// MoveHostHandler interface for that can handle valid move host params
type MoveHostHandler interface {
	Handle(MoveHostParams, interface{}) middleware.Responder
}

// NewMoveHost creates a new http.Handler for the move host operation
func NewMoveHost(ctx *middleware.Context, handler MoveHostHandler) *MoveHost {
	return &MoveHost{Context: ctx, Handler: handler}
}

/*MoveHost swagger:route POST /clusters/{cluster_id}/hosts/{host_id}/actions/move installer moveHost

move host between clusters

*/
type MoveHost struct {
	Context *middleware.Context
	Handler MoveHostHandler
}

func (o *MoveHost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMoveHostParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
