// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// NewMoveHostParams creates a new MoveHostParams object
// with the default values initialized.
func NewMoveHostParams() *MoveHostParams {
	var ()
	return &MoveHostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMoveHostParamsWithTimeout creates a new MoveHostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMoveHostParamsWithTimeout(timeout time.Duration) *MoveHostParams {
	var ()
	return &MoveHostParams{

		timeout: timeout,
	}
}

// NewMoveHostParamsWithContext creates a new MoveHostParams object
// with the default values initialized, and the ability to set a context for a request
func NewMoveHostParamsWithContext(ctx context.Context) *MoveHostParams {
	var ()
	return &MoveHostParams{

		Context: ctx,
	}
}

// NewMoveHostParamsWithHTTPClient creates a new MoveHostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMoveHostParamsWithHTTPClient(client *http.Client) *MoveHostParams {
	var ()
	return &MoveHostParams{
		HTTPClient: client,
	}
}

/*MoveHostParams contains all the parameters to send to the API endpoint
for the move host operation typically these are written to a http.Request
*/
type MoveHostParams struct {

	/*ClusterID
	  The cluster of the host that it's currently belings to.

	*/
	ClusterID strfmt.UUID
	/*HostID
	  The host that that is going to be moved between clusters.

	*/
	HostID strfmt.UUID
	/*NewClusterID
	  The destination cluster ID.

	*/
	NewClusterID *models.ClusterID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the move host params
func (o *MoveHostParams) WithTimeout(timeout time.Duration) *MoveHostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the move host params
func (o *MoveHostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the move host params
func (o *MoveHostParams) WithContext(ctx context.Context) *MoveHostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the move host params
func (o *MoveHostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the move host params
func (o *MoveHostParams) WithHTTPClient(client *http.Client) *MoveHostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the move host params
func (o *MoveHostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the move host params
func (o *MoveHostParams) WithClusterID(clusterID strfmt.UUID) *MoveHostParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the move host params
func (o *MoveHostParams) SetClusterID(clusterID strfmt.UUID) {
	o.ClusterID = clusterID
}

// WithHostID adds the hostID to the move host params
func (o *MoveHostParams) WithHostID(hostID strfmt.UUID) *MoveHostParams {
	o.SetHostID(hostID)
	return o
}

// SetHostID adds the hostId to the move host params
func (o *MoveHostParams) SetHostID(hostID strfmt.UUID) {
	o.HostID = hostID
}

// WithNewClusterID adds the newClusterID to the move host params
func (o *MoveHostParams) WithNewClusterID(newClusterID *models.ClusterID) *MoveHostParams {
	o.SetNewClusterID(newClusterID)
	return o
}

// SetNewClusterID adds the newClusterId to the move host params
func (o *MoveHostParams) SetNewClusterID(newClusterID *models.ClusterID) {
	o.NewClusterID = newClusterID
}

// WriteToRequest writes these params to a swagger request
func (o *MoveHostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID.String()); err != nil {
		return err
	}

	// path param host_id
	if err := r.SetPathParam("host_id", o.HostID.String()); err != nil {
		return err
	}

	if o.NewClusterID != nil {
		if err := r.SetBodyParam(o.NewClusterID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
